//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvionicsEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvionicsEditor.Resources.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -3000, -3000, 0.0
        ///-3000, -2990, 0.0
        ///-3000, -2980, 0.0
        ///-3000, -2970, 0.0
        ///-3000, -2960, 0.0
        ///-3000, -2950, 0.0
        ///-3000, -2940, 0.0
        ///-3000, -2930, 0.0
        ///-3000, -2920, 0.0
        ///-3000, -2910, 0.0
        ///-3000, -2900, 0.0
        ///-3000, -2890, 0.0
        ///-3000, -2880, 0.0
        ///-3000, -2870, 0.0
        ///-3000, -2860, 0.0
        ///-3000, -2850, 0.0
        ///-3000, -2840, 0.0
        ///-3000, -2830, 0.0
        ///-3000, -2820, 0.0
        ///-3000, -2810, 0.0
        ///-3000, -2800, 0.0
        ///-3000, -2790, 0.0
        ///-3000, -2780, 0.0
        ///-3000, -2770, 0.0
        ///-3000, -2760, 0.0
        ///-3000, -2750, 0.0
        ///-3000, -2740, 0.0
        ///-3000, -2730, 0.0
        ///-3000, - [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string GroundLevels {
            get {
                return ResourceManager.GetString("GroundLevels", resourceCulture);
            }
        }
    }
}
